### ISSUE TITLE
Broken icons

### ISSUE THREAD

**Issue by IonicaBizau** [numixproject/numix-icon-theme-utouch#5]
I using the [Numix uTouch icon theme](https://github.com/numixproject/numix-icon-theme-utouch) which is really cool.

I downloaded the repository and moved the folder in `/usr/share/icons`. However there are still some broken icons:

### In the top panel

![image](https://cloud.githubusercontent.com/assets/2864371/5797331/a897a240-9fc0-11e4-9504-25a14ecb4d37.png)

### Folders

![image](https://cloud.githubusercontent.com/assets/2864371/5797335/c10dfd88-9fc0-11e4-9566-453f993cefda.png)

I guess this is not the inteded behavior. How can I fix this?

<sub>Moved from https://github.com/numixproject/numix-icon-theme-technic/issues/2</sub>

**Comment by robocoder-db** [comment]
Are you using version 3 or 2? If you got it from GitHub, did you get it
from branch version3 (default) or master? If you got it from the PPA, it
will be version 2.

**Comment by IonicaBizau** [comment]
3, because I downloaded it from GitHub, the master branch. But it may not be related to this set because I saw the same behavior with other icon themes. However, I'd be glad to fix the problem.

**Comment by robocoder-db** [comment]
As far as I remember, version 3 has its own folder icons, but looking in this repo it looks like there aren't any. Can you try compiling a new version from https://github.com/robocoder-db/utouch-build-scripts? Run `make && make install` (or just `make` if you don't want to install).

**Comment by robocoder-db** [comment]
Sorry, just realised, you said version 3 from the `master` branch, version 3 is from branch `version3`, version 2 is from `master`.` version3` is the default branch if you didn't select another one. Can you clarify if you got version 3 or 2? Thanks

**Comment by IonicaBizau** [comment]
> Can you clarify if you got version 3 or 2? Thanks

I downloaded the default branch, so the `version3` one. :smile: Sorry for confusion. I guessed it's master since it was default.

...compiling...

**Comment by IonicaBizau** [comment]
I created a PR with the recompiled icons. I'm not sure if everything is OK since some directories were removed. Anyway, this issue is fixed! Thanks!

**Comment by robocoder-db** [comment]
OK, cool. Are you on something Ubuntu-based BTW? Because the build script
dependencies are a nightmare to install without Ubuntu

**Comment by robocoder-db** [comment]
Ignore that, I just saw your last message

**Comment by IonicaBizau** [comment]
Yes, I'm on Ubuntu 14.10.
