### ISSUE TITLE
uTouch isn't in the Numix PPA

### ISSUE THREAD

**Issue by FlourishFlora** [numixproject/numix-icon-theme-utouch#8]
The installation insturctions on the README don't work. If I type "sudo apt-get install numix-icon-theme-utouch", I get "Unable to locate package numix-icon-theme-utouch". You can see from the [Numix PPA page](https://launchpad.net/~numix/+archive/ubuntu/ppa) that uTouch isn't there. Why is that? Is there another way to get the uTouch installation package?

**Comment by satya164** [comment]
uTouch isn't officially supported any more. You have to install it by getting it from git.
